function dropdownHandle = makeDropdown(parent, choices, position, fontSize, funcNameHandle) 
% To make code more readable use this funciton when setting up dropdowns
% parent is the tab or figure that the object is located on
% choices is a cell array containing character array of the dropdown's
% chioces
% position is a 1x4 array [x y w h] where x is the distance from
% the left side of the figure, y is the distance from the bottom of
% the figure, w is the width of the textbox, and h is the height of
% the object.
% fontSize is the size of the text
% funcNameHandle is the name of the callback function to be associated with
% the dropdown and must be preceded by an @ sign.

dropdownHandle = uicontrol(parent, ...
    'Style', 'popupmenu', ...
    'String', choices, ...
    'Position', position, ...
    'Value', 1, ...
    'Units', 'normalized', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', fontSize, ...
    'Callback', funcNameHandle);
end