function hBuildMenu = open_editdevice
    list = getBuiltDevices;
    
    if ( size(list) ~= 0)
        hExistingDevMenu = figure('Visible', 'on', ...
            'Position', [500, 50, 550, 575], ...
            'Name', 'Availible Devices', ...
            'NumberTitle', 'off', ...
            'MenuBar', 'none', ...
            'Units', 'normalized', ...
            'ToolBar', 'none');
        
        hTitleText = uicontrol(hExistingDevMenu, ...
            'Style', 'text', ...
            'String', 'Select the device you would like to work with', ...
            'Position', [15, 510, 350, 40], ...
            'Units', 'normalized', ...
            'FontSize', 14);

        hListBox = uicontrol(hExistingDevMenu, ...
            'style','listbox',...
            'position',[200, 175, 150, 150],...
            'fontsize',12,...
            'fontweight','bold',... 
            'string',list,...
            'Callback', @AddDev, ...
            'value',1);

    else
        answer = questdlg('No Built Devices Found. Do you want to create a new device?', ...
        'Yes', 'No', 'No');
        switch answer
            case 'Yes'
                device = defaultDevObj();
                hBuildMenu = open_devname(device, 0);
            case 'No'
                % Do Nothing
        end
    end

    uiwait(hExistingDevMenu);
    currentFolder = pwd;
    filename = [currentFolder '\GUI_Devices\' ...
        hListBox.String{hListBox.Value} '.GUI'];
    % Without A_load in current folder, this next line fails even if the
    % desired file is in a parent directory.
    device = A_load(filename);
    hBuildMenu = openBuildMenu(device);
    
    
end

function AddDev(hObject, ~)
     uiresume(hObject.Parent);
end


   