function hBulkMenu = openBulkMenu(devObj, newCheck)
% open bulk device menu using class's current properties

global CONST

% create and then hide the UI as it is being constructed ------------------
hBulkMenu = figure('Visible', 'off', ...
    'Position', [775, 50, 750, 775], ...
    'Name', 'Set Parameters for Bulk of Device', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'Units', 'normalized', ...
    'ToolBar', 'none');

hBulkTabs = uitabgroup(hBulkMenu);

hBasicTab = uitab(hBulkTabs, 'Title', 'Basic Parameters');
hMobilityTab = uitab(hBulkTabs, 'Title', 'Mobility');
hDopingTab = uitab(hBulkTabs, 'Title', 'Doping');
hRecomTab = uitab(hBulkTabs, 'Title', 'Recombination');
hOptTab = uitab(hBulkTabs, 'Title', 'Optical Generation');
hAbsorpTab = uitab(hBulkTabs, 'Title', 'Parasitic Absorption');

% Set default object parameters if device is new --------------------------
if newCheck == 1
    
end 

% Construct the UI --------------------------------------------------------
% Basic Tab
hModelNameText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Semiconductor Model Name:', ...
    'Position', [15, 735, 210, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hModelNameEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', 'Simple', ...
    'Position', [15, 710, 210, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateModelName);

hThicknessText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Layer Thickness:', ...
    'Position', [15, 660, 125, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hThicknessEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '-999', ...
    'Position', [15, 635, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateThickness);

hThicknessUnitDropdown = uicontrol(hBasicTab, ...
    'Style', 'popupmenu', ...
    'String', {'cm', 'um', 'nm', 'A'}, ...
    'Position', [70, 635, 50, 20], ...
    'Value', 1, ...
    'Units', 'normalized');
    
hEleAffinText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Electron Affinity (eV):', ...
    'Position', [15, 585, 155, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hEleAffinEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '4', ...
    'Position', [15, 560, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateEleAffin);

hBandgapText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Bandgap (eV):', ...
    'Position', [15, 510, 110, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hBandgapEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '1', ...
    'Position', [15, 485, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateBandgap);

hDieleConstText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Dielectric Constant:', ...
    'Position', [15, 435, 150, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hDieleConstEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '10', ...
    'Position', [15, 410, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateDieleConst);

hConductBandText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Conduction Band Effective Density of States (#/cm^3):', ...
    'Position', [15, 360, 390, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hConductBandEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '1.00E+019', ...
    'Position', [15, 335, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateConductBand);

hValenceBandText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Valence Band Effective Density of States (#/cm^3):', ...
    'Position', [15, 285, 365, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hValenceBandEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '1.00E+019', ...
    'Position', [15, 255, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateValenceBand);

hElecThermVelocityText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Electron Thermal Velocity (cm/s):', ...
    'Position', [15, 210, 240, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hElecThermVelocityEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '1.00E+007', ...
    'Position', [15, 180, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateElecThermVelocity);

hHoleThermVelocityText = uicontrol(hBasicTab, ...
    'Style', 'text', ...
    'String', 'Hole Thermal Velocity (cm/s):', ...
    'Position', [15, 135, 215, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hHoleThermVelocityEdit = uicontrol(hBasicTab, ...
    'Style', 'edit', ...
    'String', '1.00E+007', ...
    'Position', [15, 105, 100, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateHoleThermVelocity);

% Mobility Tab
hHoleMobilityText = uicontrol(hMobilityTab, ...
    'Style', 'text', ...
    'String', 'Hole Mobility (cm^2/V-s):', ...
    'Position', [15, 60, 180, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hHoleMobilityEdit = uicontrol(hMobilityTab, ...
    'Style', 'edit', ...
    'String', '100', ...
    'Position', [415, 670, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateHoleMobility);

hElecMobilityText = uicontrol(hMobilityTab, ...
    'Style', 'text', ...
    'String', 'Electron Mobility (cm^2/V-s):', ...
    'Position', [415, 700, 205, 20], ...
    'FontSize', 12, ...
    'BackgroundColor', 'c', ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized');

hElecMobilityEdit = uicontrol(hMobilityTab, ...
    'Style', 'edit', ...
    'String', '100', ...
    'Position', [15, 30, 50, 20], ...
    'HorizontalAlignment', 'left', ...
    'Units', 'normalized', ...
    'Callback', @UpdateElecMobility);

% Doping Tab

% Optical Generation Tab

% Parasitic Absorption Tab

% Initialize the UI. ------------------------------------------------------
% make UI visible
hBulkMenu.Visible = 'on';

% Bulk Menu Callbacks -----------------------------------------------------
    function UpdateModelName(hObject, ~)
        % Sets the adept device model name to the entered string
        % devObj.model = hObject.String
    end

    function UpdateThickness(hObject, ~)
        % Converts entered value into cenimeters then sets the layer 
        % thickess to the converted value. Grab the units from
        % hThicknessUnitDropdown. adept object variable is any of the
        % following: t_A, t_nm, t_um, t_cm
    end

    function UpdateEleAffin(hObject, ~)
        % Sets the electron affinity to the new value. adept object
        % variable is chi
    end

    function UpdateBandgap(hObject, ~)
        % Sets the bandgap to the new value. adept object
        % variable is Eg or eg
    end

    function UpdateDieleConst(hObject, ~)
        % Sets the dielectric constant to the new value. adept object
        % variable is ks
    end

    function UpdateConductBand(hObject, ~)
        % Sets the conduction band effective density of states to the new 
        % value. adept object variable is Nc
    end
end