function hEditMenu = open_editdevice(devObj, count)
    list = getBuiltDevices;
    device = Adept;
    
    if ( size(list) ~= 0)
        hExistingDevMenu = figure('Visible', 'on', ...
            'Position', [500, 50, 550, 575], ...
            'Name', 'Availible Devices', ...
            'NumberTitle', 'off', ...
            'MenuBar', 'none', ...
            'Units', 'normalized', ...
            'ToolBar', 'none');
        
        hTitleText = uicontrol(hExistingDevMenu, ...
            'Style', 'text', ...
            'String', 'Select the device you would like to work with', ...
            'Position', [15, 510, 350, 40], ...
            'Units', 'normalized', ...
            'FontSize', 14);

        hListBox = uicontrol(hExistingDevMenu, ...
            'style','listbox',...
            'position',[200, 175, 150, 150],...
            'fontsize',12,...
            'fontweight','bold',... 
            'string',list,...
            'Callback', @AddDev, ...
            'value',1);

    else
        answer = questdlg(v, ...
        'Yes', 'No');
        switch answer
            case 'Yes'
                open_devname(device, 0);
            case 'No'
                % Do Nothing
        end
    end
   
end


function AddDev(devObj, ~)
            device  = Adept;
           device.input_file = 'Test';
           openBuildMenu(device)
        
     
    end

   